name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Configure Poetry project
        run: poetry install

      - name: Run tests with pytest
        run: poetry run pytest --junitxml=results/test-results.xml

      - name: Submit test results to testmo
        env:
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
        run: |
          curl \
            -H "Authorization: Bearer ${ZEPHYR_TOKEN}" \
            -F "file=@results/test-results.xml;type=application/xml" \
            https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey="ND"&autoCreateTestCases=true
